name: ZyrionPlay EPG Engine

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar Dependências
        run: |
          # Entramos apenas na pasta epg
          cd epg
          npm init -y
          npm install axios

      - name: Executar Script de Redundância
        # Executamos o script direto da pasta epg
        run: node epg/update_epg.js

      - name: Salvar Alterações no GitHub
        run: |
          git config --global user.name "Zyrion-Bot"
          git config --global user.email "bot@zyrionplay.com"
          # Adicionamos o arquivo gerado na pasta epg
          git add epg/epg_final.xml
          git commit -m "Bot: EPG atualizado via redundância [$(date)]" || echo "Sem alterações"
          git push
