name: ZyrionPlay EPG Engine

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar Axios na pasta correta
        run: |
          cd zyrion/epg
          npm init -y
          npm install axios

      - name: Executar Script de Redundância
        run: node zyrion/epg/update_epg.js

      - name: Salvar Alterações no GitHub
        run: |
          git config --global user.name "Zyrion-Bot"
          git config --global user.email "bot@zyrionplay.com"
          git add zyrion/epg/epg_final.xml
          git commit -m "Bot: EPG atualizado via redundância [$(date)]" || echo "Sem alterações"
          git push
